/*
*----------------------------------------------------------------------
*  Common.c
*
*  Source file for common APIs of application
*
*----------------------------------------------------------------------
*/

/*
*----------------------------------------------------------------------
*  File:              Common.c
*  Created by:        Dhanyakumar H C (Student ID : 2024HT01096)
*----------------------------------------------------------------------
*/

/*
*----------------------------------------------------------------------
*   Include Files
*----------------------------------------------------------------------
*/

#include "Common.h"



/*
*----------------------------------------------------------------------
*   Private Defines
*----------------------------------------------------------------------
*/




/*
*----------------------------------------------------------------------
*   Private Macros
*----------------------------------------------------------------------
*/

/*
*----------------------------------------------------------------------
*   Private Data Types
*----------------------------------------------------------------------
*/


/*
*----------------------------------------------------------------------
*   Public Variables
*----------------------------------------------------------------------
*/


/*
*----------------------------------------------------------------------
*   Private Variables (static)
*----------------------------------------------------------------------
*/
BOOL USB_DriveConnectionStatus = FALSE;

/*
*----------------------------------------------------------------------
*   Public Constants
*----------------------------------------------------------------------
*/

/*
*----------------------------------------------------------------------
*   Private Constants (static)
*----------------------------------------------------------------------
*/


/*
*----------------------------------------------------------------------
*   Private Function Prototypes (static)
*----------------------------------------------------------------------
*/
static const CHAR ProtocolString[PROTOCOL_MAX][20] =
{
   "MODBUS",
   "CAN",
   "SERIAL_ASCII"
};

static const CHAR ParameterAccessType[PAT_MAX][20] =
{
   "read_only",
   "read_write",
};

static const CHAR ParameterDataType[PDT_UNKNOWN][20] =
{
   "int_8", 	// PDT_INT8 = 0,
   "uint_8", 	// PDT_UINT8,
   "char", 		// PDT_CHAR,
   "uchar", 	// PDT_UCHAR,
   "int_16", 	// PDT_INT16,
   "uint_16", 	// PDT_UINT16,
   "int_32", 	// PDT_INT32,
   "uint_32", 	// PDT_UINT32,
   "float", 	// PDT_FLOAT,
   "string", 	// PDT_STRING,
};

static const CHAR ParameterNameString_MODBUS[PAR_ID_MAX][30] =
{
  "NONE",                             // PAR_ID_NONE
  "TEMPERATURE",                      // PAR_ID_TEMPERATURE
  "TEMPERATURE_SET_POINT",            // PAR_ID_TEMPERATURE_SET_POINT
  "DEV_STATUS",                       // PAR_ID_DEV_STATUS
  "PRESSURE",                         // PAR_ID_PRESSURE
  "DUTY_CYCLE",                       // PAR_ID_DUTY_CYCLE
  "ALARM_BITS",                       // PAR_ID_ALARM_BITS
  "DEV_NAME",                         // PAR_ID_DEV_NAME
};
/*
*----------------------------------------------------------------------
*   Private Functions
*----------------------------------------------------------------------
*/

/*
*----------------------------------------------------------------------
*   Public Functions
*----------------------------------------------------------------------
*/
/*
*----------------------------------------------------------------------
*  Name     : AppDelay
*
*  Summary  : This function uses delay function based on OS running status
*
*  Input    : time in milli seconds
*
*  Output   : void
*
*  Return   : t_Status
*
*  Notes    :
*
*----------------------------------------------------------------------
*/
void AppDelay(UINT32 MilliSec)
{
   // use HAL delay
    HAL_Delay(MilliSec);
}
/*
*----------------------------------------------------------------------
*  Name     : SystemClock_Config
*
*  Summary  : This function initializes system clock and peripheral
*             clock. Configures 16MHz system clock using internal RC
*             HSI
*
*             This function generated by STMCubeMx
*
*  Input    : void
*
*  Output   : void
*
*  Return   : t_Status
*
*  Notes    : This function must be called as soon as device wakes up
*             from stop mode
*
*----------------------------------------------------------------------
*/
t_Status SystemClock_Config(void)
{
   t_Status ReturnValue = STS_OK;

   RCC_OscInitTypeDef RCC_OscInitStruct = {0};
   RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

   /** Initializes the RCC Oscillators according to the specified parameters
   * in the RCC_OscInitTypeDef structure.
   */
   RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
   RCC_OscInitStruct.HSIState = RCC_HSI_ON;
   RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
   RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
   RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI_DIV2;
   RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL16;
   if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
   {
	   ReturnValue = STS_ERROR;
   }

   /** Initializes the CPU, AHB and APB buses clocks
   */
   RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                               |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
   RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
   RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
   RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
   RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

   if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
   {
	   ReturnValue = STS_ERROR;
   }

   return ReturnValue;

#if 0
   RCC_OscInitTypeDef RCC_OscInitStruct = {0};
   RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

   /** Initializes the RCC Oscillators according to the specified parameters
   * in the RCC_OscInitTypeDef structure.
   */
   RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
   RCC_OscInitStruct.HSIState = RCC_HSI_ON;
   RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
   RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
   RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI_DIV2;
   RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL16;
   if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
   {
     Error_Handler();
   }

   /** Initializes the CPU, AHB and APB buses clocks
   */
   RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                               |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
   RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
   RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
   RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
   RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

   if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
   {
     Error_Handler();
   }
#endif
}


/*
*----------------------------------------------------------------------
*  Name     : DelayMs
*
*  Summary  : Blocked delay function. Kills processor time given time
*
*  Input    : time in milli seconds (0 to 999ms)
*
*  Output   : void
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
void DelayMs(UINT16 TimeIn_msec)
{
   // Call HAL delay function which uses system tick time to calculate delay
   AppDelay((UINT32)TimeIn_msec);
}
/*
*----------------------------------------------------------------------
*  Name     : DelayMs
*
*  Summary  : Blocked delay function. Kills processor time given time
*
*  Input    : time in  seconds (0 to 255)
*
*  Output   : void
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
void DelaySecs(UINT8 TimeIn_Sec)
{
   // convert time in to ms
   //g_lMsDelayTimer = (UINT32)(TimeIn_Sec*1000);

   // g_lMsDelayTimer decremented in SYS tick ISR

   // wait until timer expires
   //while(g_lMsDelayTimer > 0);
}
/*
 *----------------------------------------------------------------------
 *  Name    : Checksum_8BIT
 *
 *  Summary :
 *
 *  Input   :
 *
 *  Output  :
 *
 *  Return  :
 *
 *  Notes:
 *
 *----------------------------------------------------------------------
 */
UINT8 Checksum_8BIT(UINT8 *pBuffer, UINT32 Size)
{
   UINT8 Checksum = 0;
   UINT32 Index = 0;

   for(Index = 0; Index < Size; Index++)
   {
      Checksum = (UINT8)(Checksum + pBuffer[Index]);
   }

   return Checksum;
}
/*
*----------------------------------------------------------------------
*  Name     : CalculateChecksum_Fletcher16
*
*  Summary  : This function calculate checksum using Fletcher16 algorithm
*
*  Input    : void
*
*  Output   : void
*
*  Returns  : Calculated checksum
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
UINT16 CalculateChecksum_Fletcher16(UINT8 *pData, UINT16 Count)
{
   UINT16 Sum_1 = 0;
   UINT16 Sum_2 = 0;
   UINT16 index;

   for( index = 0; index < Count; ++index )
   {
      Sum_1 = (Sum_1 + pData[index]) % 255;
      Sum_2 = (Sum_2 + Sum_1) % 255;
   }

   return (Sum_2 << 8) | Sum_1;
}

/*
*----------------------------------------------------------------------
*  Name     : CalculateChecksum_Fletcher32
*
*  Summary  : This function calculate checksum using Fletcher32 algorithm
*
*  Input    : void
*
*  Output   : void
*
*  Returns  : Calculated checksum
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
UINT32 CalculateChecksum_Fletcher32(const UINT16 *pData, UINT32 Count)
{
   UINT32 c0, c1;
   UINT32 i;

   for (c0 = c1 = 0; Count >= 360; Count -= 360)
   {
      for (i = 0; i < 360; ++i)
      {
         c0 = c0 + *pData++;
         c1 = c1 + c0;
      }
      c0 = c0 % 65535;
      c1 = c1 % 65535;
   }

   for (i = 0; i < Count; ++i)
   {
      c0 = c0 + *pData++;
      c1 = c1 + c0;
   }

   c0 = c0 % 65535;
   c1 = c1 % 65535;

   return (c1 << 16 | c0);
}

/*
*----------------------------------------------------------------------
*  Name     : CountBitInbytes
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
UINT16 CountBitInbytes(void *pBuff, UINT16 NoOfBytes)
{
   UINT16 BitsCount = 0;
   UINT16 Index, BitIndex;
   UINT8  *pBytes = (UINT8*)pBuff;

   if(pBuff != NULL)
   {
      for(Index = 0; Index < NoOfBytes; Index++)
      {
         for(BitIndex = 0; BitIndex < 8; BitIndex++)
         {
            if(pBytes[Index] & (0x01 << BitIndex))
            {
               BitsCount++;
            }
         }
      }
   }

   return BitsCount;
}
/*
*----------------------------------------------------------------------
*  Name     : TrimWhiteSpaceInString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
UCHAR *TrimWhiteSpaceInString(UCHAR *str)
{
   UCHAR *end;

  // Trim leading space
  while(isspace((UCHAR)*str)) str++;

  if(*str == 0)  // All spaces?
    return str;

  // Trim trailing space
  end = str + strlen(str) - 1;

  while(end > str && isspace((unsigned char)*end)) end--;

  // Write new null terminator character
  end[1] = '\0';

  return str;
}
/*
*----------------------------------------------------------------------
*  Name     : TrimWhiteSpaceInString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
void ExtractSubString(UCHAR *pInput, UCHAR *pOutput, UCHAR StartChar, UCHAR EndChar, UINT16 BuffSize)
{
   UINT16  StartIndex = 0, EndIndex = 0, Index = 0;;

   if((pInput != NULL) && (pOutput != NULL))
   {
      memset(pOutput, 0x00, BuffSize);

      // check all characters
      while((pInput[Index]) != 0)
      {
         if((pInput[Index]) == StartChar)
         {
            StartIndex = Index + 1;
         }

         if((pInput[Index]) == EndChar)
         {
            EndIndex = Index;
            break;
         }

         // increment input string
         Index++;
      }

      if((EndIndex > StartIndex) &&
         ((EndIndex - StartIndex) < BuffSize))
      {
         strncpy(pOutput, &pInput[StartIndex], (EndIndex - StartIndex));
      }
   }
}
/*
*----------------------------------------------------------------------
*  Name     : StringToMacAddress
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
BOOL StringToMacAddress(const CHAR* pMacAddress, UINT8* pValues)
{
   // convert string to MAC address
   if(6 == sscanf((char*)pMacAddress, "%02x:%02x:%02x:%02x:%02x:%02x",&pValues[0],
                  &pValues[1], &pValues[2],&pValues[3], &pValues[4], &pValues[5]))
   {
      return TRUE;
   }
   else
   {
      return FALSE;
   }
}
/*
*----------------------------------------------------------------------
*  Name     : StringToIPv4Address
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
BOOL StringToIPv4Address(const CHAR* pIPv4Address, UINT8* pValues)
{
   // convert string to MAC address
   if(4 == sscanf((char*)pIPv4Address, "%03d.%03d.%03d.%03d", &pValues[0],
                  &pValues[1], &pValues[2],&pValues[3]))
   {
      return TRUE;
   }
   else
   {
      return FALSE;
   }
}
/*
*----------------------------------------------------------------------
*  Name     : StringToIPv6Address
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
BOOL StringToIPv6Address(const CHAR* pIPv6Address, UINT16* pValues)
{
   // convert string to MAC address
   if(8 == sscanf((char*)pIPv6Address, "%04X:%04X:%04X:%04X:%04X:%04X:%04X:%04X", &pValues[0],
                  &pValues[1], &pValues[2],&pValues[3],&pValues[4],&pValues[5],&pValues[6],&pValues[7]))
   {
      return TRUE;
   }
   else
   {
      return FALSE;
   }
}
/*
*----------------------------------------------------------------------
*  Name     : IPv4AddressToString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
BOOL IPv4AddressToString(const UINT8* pValues, CHAR *pIPv4Address, UINT8 BuffSize)
{
   // convert IPv4 to string address
   snprintf((char*)pIPv4Address, BuffSize, "%03d.%03d.%03d.%03d", pValues[0], pValues[1], pValues[2], pValues[3]);

   return TRUE;
}
/*
*----------------------------------------------------------------------
*  Name     : IPv6AddressToString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
BOOL IPv6AddressToString(const UINT16* pValues, CHAR *pIPv6Address, UINT8 BuffSize)
{
   // convert IPv4 to string address
   snprintf((char*)pIPv6Address, BuffSize, "%04X:%04X:%04X:%04X:%04X:%04X:%04X:%04X", pValues[0], pValues[1],
            pValues[2], pValues[3], pValues[4], pValues[5], pValues[6], pValues[7]);

   return TRUE;
}
/*
*----------------------------------------------------------------------
*  Name     : MacAddressToString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
BOOL MacAddressToString(const UINT8* pValues, CHAR *pMacAddress, UINT8 BuffSize)
{
   // convert IPv4 to string address
   snprintf((char*)pMacAddress, BuffSize, "%02x:%02x:%02x:%02x:%02x:%02x", pValues[0], pValues[1], pValues[2], pValues[3], pValues[4], pValues[5]);

   return TRUE;
}
/*
*----------------------------------------------------------------------
*  Name     : GetProtocolString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
const CHAR* GetProtocolString(t_Protocol Protocol)
{
	if(Protocol < PROTOCOL_MAX)
	{
		return ProtocolString[Protocol];
	}
	else
	{
		return NULL;
	}
}
/*
*----------------------------------------------------------------------
*  Name     : GetAccessString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
const CHAR* GetAccessString(t_ParamAcessType access)
{
	if(access < PAT_MAX)
	{
		return ParameterAccessType[access];
	}
	else
	{
		return NULL;
	}
}
/*
*----------------------------------------------------------------------
*  Name     : GetDataTypeString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
const CHAR* GetDataTypeString(t_ParamDataType datatype)
{
	if(datatype < PDT_UNKNOWN)
	{
		return ParameterDataType[datatype];
	}
	else
	{
		return NULL;
	}
}

/*
*----------------------------------------------------------------------
*  Name     : GetParameterIDFromString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
const CHAR* GetParameterNameString(UINT16 ParamID, t_Protocol Protocol)
{

	switch(Protocol)
	{
		case  MODBUS :   return ParameterNameString_MODBUS[ParamID]; break;

		case  CAN :
		case  SERAIL_ASCII:
		default:
			return NULL;
		break;

	}
}

/*
*----------------------------------------------------------------------
*  Name     : GetParameterIDFromString
*
*  Summary  :
*
*  Input    : void
*
*  Output   : void
*
*  Returns  :
*
*  Notes    : NA
*
*----------------------------------------------------------------------
*/
UINT16  GetParameterIDFromString(const CHAR *pParameterName, t_Protocol Protocol)
{
    UINT16 ParamID = 0xFFFF; // invalid parameter ID

	switch(Protocol)
	{
		case  MODBUS :  
      {
         UINT16 Index = 0;


         for(Index = 0; Index < PAR_ID_MAX; Index++)
         {
            if(strcmp(pParameterName, ParameterNameString_MODBUS[Index]) == 0)
            {
               ParamID = Index;
               break;
            }
         }
         return ParamID;
      }
      break;

		case  CAN :
		case  SERAIL_ASCII:
		default:
			break;

	}

	return ParamID;
}


t_Status GetProtocolIDandAddressFromString(const CHAR *pDeviceString, t_Protocol *pProtocol, UINT16 *pAddress)
{
   t_Status ReturnValue = STS_OK;

   // Extract protocol string from device string
   CHAR ProtocolString[40];
   CHAR DeviceAddressString[40];
   UINT16 Index = 0;
   UINT16 Length = strlen(pDeviceString);

   memset(ProtocolString, 0x00, sizeof(ProtocolString));
   memset(DeviceAddressString, 0x00, sizeof(DeviceAddressString));

   // extract sub string till '_' and store in ProtocolString, from 0th indet to '_' character
   for(Index = 0; Index < Length && Index < sizeof(ProtocolString) - 1; Index++)
   {
      if(pDeviceString[Index] == '_')
      {
         ProtocolString[Index] = '\0';
         break;
      }
      else
      {
         ProtocolString[Index] = pDeviceString[Index];
      }
   }

   // copy deevice address string from device string to DeviceAddressString, from '_' character to end of string
   if(Index < Length)
   {
      strncpy(DeviceAddressString, &pDeviceString[Index + 1], Length - Index - 1);

      DeviceAddressString[Length - Index - 1] = '\0';

      // convert device address string to integer
      *pAddress = (UINT16)atoi(DeviceAddressString);
   }
   else
   {
	   *pAddress = 0xFFFF; // if address is not present in string, assign invalid address
   }

   // now compare extracted protocol string with known protocol strings and get protocol ID
   if(strcmp(ProtocolString, "MODBUS") == 0)
   {
      *pProtocol = MODBUS;
   }
   else if(strcmp(ProtocolString, "CAN") == 0)
   {
      *pProtocol = CAN;
   }
   else if(strcmp(ProtocolString, "SERIAL_ASCII") == 0)
   {
      *pProtocol = SERAIL_ASCII;
   }
   else
   {
      ReturnValue = STS_ERROR_MODULENOTDEFINED;
   }

   return ReturnValue;
}
/*
 *  End of File
 */

